actions:
    index:
        route: 'sudo_wh_superadmin_menu_index'
    create:
        route: 'sudo_wh_superadmin_menu_create'
    update:
        route: 'sudo_wh_superadmin_menu_update'
        parameters:
            - id

menus:
    main: 'menu-superadmin'
    right: 'menu-superadmin-right'