title: 'Liste des menus'
breadcrumb:
    index:
        label: 'Liste des menus'
        action: 'index'

tablePanelProperties:
    headerLabel: 'Liste des menus'
    headerListButtons:
        create:
            buttonType: 'link'
            color: 'success'
            label: 'Créer un menu'
            action: 'create'
            modal: 'true'
            size: 'xs'
    tableFields:
        buttons:
            update:
                icon: 'pencil'
                modal: 'true'
                route: 'sudo_wh_superadmin_menu_update'
                routeParams:
                    id: 'id'
            delete:
                icon: 'trash'
                color: 'danger'
                route: 'sudo_wh_superadmin_menu_delete'
                routeParams:
                    id: 'id'
                confirm: 'Êtes-vous sûr de vouloir supprimer ce menu ?'
            items:
                icon: 'gear'
                color: 'info'
                route: 'sudo_wh_superadmin_menuitem_index'
                routeParams:
                    menuId: 'id'
        id: 'ID'
        name: 'Nom'