actions:
    index:
        route: 'sudo_wh_superadmin_menuitem_index'
        parameters:
            menuId: 'menu.id'
    order:
        route: 'sudo_wh_superadmin_menuitem_order'
        parameters:
            menuId: 'menu.id'
    create:
        route: 'sudo_wh_superadmin_menuitem_create'
        parameters:
            menuId: 'menu.id'
    update:
        route: 'sudo_wh_superadmin_menuitem_update'
        parameters:
            id: 'id'
    delete:
        route: 'sudo_wh_superadmin_menuitem_delete'
        parameters:
            id: 'id'

formFields:
    name:
        label: 'Nom'
        field: 'name'
        type: 'text'
    route:
        label: 'Route'
        field: 'route'
        type: 'text'
    parent:
        label: 'Parent'
        field: 'parent'
        type: 'entity'
        class: 'WHSuperAdminBundle:MenuItem'
        choice_label: 'indentedName'

menus:
    main: 'super-admin-menu'
    right: 'super-admin-menu-right'