modal: 'true'

title: 'Editer un item de menu'

formFields:
    - name
    - route
    - parent

footerFormFields:
    save:
        label: 'Enregistrer'
        field: 'save'
        color: 'success'