modal: 'true'

title: 'Editer un item de menu'

formFields:
    name:
        label: 'Nom'
        field: 'name'
        type: 'text'
    route:
        label: 'Route'
        field: 'route'
        type: 'text'
    parent:
        label: 'Parent'
        field: 'parent'
        type: 'entity'
        class: 'WHSuperAdminBundle:MenuItem'
        choice_label: 'indentedName'

footerFormFields:
    save:
        label: 'Enregistrer'
        field: 'save'
        color: 'success'